// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    return $('#experience-expander').on('click', function() {
      $('#experience-more').toggle();
      return $(this).text($(this).text() === 'More' ? 'Less' : 'More');
    });
  });

}).call(this);
